// Code generated by MockGen. DO NOT EDIT.
// Source: ./modules/jwt.go

// Package modules is a generated GoMock package.
package modules

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockJsonWebTokenUtilInterface is a mock of JsonWebTokenUtilInterface interface.
type MockJsonWebTokenUtilInterface struct {
	ctrl     *gomock.Controller
	recorder *MockJsonWebTokenUtilInterfaceMockRecorder
}

// MockJsonWebTokenUtilInterfaceMockRecorder is the mock recorder for MockJsonWebTokenUtilInterface.
type MockJsonWebTokenUtilInterfaceMockRecorder struct {
	mock *MockJsonWebTokenUtilInterface
}

// NewMockJsonWebTokenUtilInterface creates a new mock instance.
func NewMockJsonWebTokenUtilInterface(ctrl *gomock.Controller) *MockJsonWebTokenUtilInterface {
	mock := &MockJsonWebTokenUtilInterface{ctrl: ctrl}
	mock.recorder = &MockJsonWebTokenUtilInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJsonWebTokenUtilInterface) EXPECT() *MockJsonWebTokenUtilInterfaceMockRecorder {
	return m.recorder
}

// GenerateJwt mocks base method.
func (m *MockJsonWebTokenUtilInterface) GenerateJwt(claims CustomClaims) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateJwt", claims)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateJwt indicates an expected call of GenerateJwt.
func (mr *MockJsonWebTokenUtilInterfaceMockRecorder) GenerateJwt(claims interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateJwt", reflect.TypeOf((*MockJsonWebTokenUtilInterface)(nil).GenerateJwt), claims)
}

// VerifyJwt mocks base method.
func (m *MockJsonWebTokenUtilInterface) VerifyJwt(tokenString string) (*CustomClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyJwt", tokenString)
	ret0, _ := ret[0].(*CustomClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyJwt indicates an expected call of VerifyJwt.
func (mr *MockJsonWebTokenUtilInterfaceMockRecorder) VerifyJwt(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyJwt", reflect.TypeOf((*MockJsonWebTokenUtilInterface)(nil).VerifyJwt), tokenString)
}
