// Code generated by MockGen. DO NOT EDIT.
// Source: ./modules/password.go

// Package modules is a generated GoMock package.
package modules

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPasswordAuthInterface is a mock of PasswordAuthInterface interface.
type MockPasswordAuthInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordAuthInterfaceMockRecorder
}

// MockPasswordAuthInterfaceMockRecorder is the mock recorder for MockPasswordAuthInterface.
type MockPasswordAuthInterfaceMockRecorder struct {
	mock *MockPasswordAuthInterface
}

// NewMockPasswordAuthInterface creates a new mock instance.
func NewMockPasswordAuthInterface(ctrl *gomock.Controller) *MockPasswordAuthInterface {
	mock := &MockPasswordAuthInterface{ctrl: ctrl}
	mock.recorder = &MockPasswordAuthInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordAuthInterface) EXPECT() *MockPasswordAuthInterfaceMockRecorder {
	return m.recorder
}

// CompareHashedPassword mocks base method.
func (m *MockPasswordAuthInterface) CompareHashedPassword(hashedPassword, password string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareHashedPassword", hashedPassword, password)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompareHashedPassword indicates an expected call of CompareHashedPassword.
func (mr *MockPasswordAuthInterfaceMockRecorder) CompareHashedPassword(hashedPassword, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareHashedPassword", reflect.TypeOf((*MockPasswordAuthInterface)(nil).CompareHashedPassword), hashedPassword, password)
}

// GenerateHashedPassword mocks base method.
func (m *MockPasswordAuthInterface) GenerateHashedPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateHashedPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateHashedPassword indicates an expected call of GenerateHashedPassword.
func (mr *MockPasswordAuthInterfaceMockRecorder) GenerateHashedPassword(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateHashedPassword", reflect.TypeOf((*MockPasswordAuthInterface)(nil).GenerateHashedPassword), password)
}
